### ISSUE TITLE
Finish and publish mapit.poplus.org

### ISSUE THREAD

**Issue by TomSteinberg** [mysociety/mapit.poplus.org#4]
This means:
- Double checking the copy of the new homepage
- Making sure documentation links point to the right places
- Cutting out anything incomplete or that requires further coding

**Comment by zarino** [comment]
Note to self: If the page is advertising both MapIt as a service (global.mapit.mysociety.org) and MapIt as a component, any claims on the page need to be either true for both, or clearly signposted as to which version they apply to.

eg: Rate limiting only applies to the hosted version. And while the self-hosted version _does_ use OpenStreetMap to render map tiles, it _doesn't_ use any geographical data from OpenStreetMap.

Also, the "Licensing" page shows licensing information for Mapit as a service, rather than MapIt as a component, which probably isn't right.

**Comment by zarino** [comment]
Taking the precedent set by popit.poplus.org, this is what we've got so far:

![mapit 20140606](https://cloud.githubusercontent.com/assets/739624/3199188/9950afc0-ed64-11e3-98c4-ad1c9ccf564b.png)

(not sure why the top navbar links haven't come out in the screenshot, but they're still "About  Documentation  License  Github" as on mapit.poplus.org)

I don't know whether the distinction between MapIt Global/UK (the hosted services) and the self-hosted component are clear enough, or whether, in fact, we sort of don't want to draw attention to the difference until they click "Get started"… @TomSteinberg thoughts?

**Comment by TomSteinberg** [comment]
Looking much better. Here are some copy suggestions
- Main title - 'Solve your app's administrative boundary problems, easily'
- Subtitle - 'If your app or website needs to connect locations with administrative areas, like wards or counties, MapIt can save you a lot of time. Available as a hosted API or a self-deployed web service, to suit your needs.'
- What is Mapit?
  1 - MapIt turns geographic points into areas - So 48.85, 2.35 becomes Paris.
  2 - Is all about the APIs - whether you self-host or use a hosted version, you get the data RESTfully
  3 - Can be self-hosted - Deploy an instance and fill it with whatever boundaries you want
  4 - Is also available hosted - Versions pre-loaded with data exist for various areas

Also I'd drop the 'see it in action' button, and when a user clicks 'get started' I think it should scroll down to the 'Collect and query' section.

Then in that section the two buttons should be 'Host MapIt yourself' or 'Learn about hosted versions'

**Comment by zarino** [comment]
![screen shot 2014-06-06 at 12 37 53](https://cloud.githubusercontent.com/assets/739624/3199746/060fe48c-ed6f-11e3-85e7-7a8027a86f80.png)

**Comment by davewhiteland** [comment]
Tiny suggestion: don't use the word "wards" because very few people know what that means, especially outside of the UK. I think "constituencies" may be better because it's likely Google translate or a dictionary lookup is going to be right enough, and it's especially relevant to the PMO space we're often using it in ourselves.

Subtitle - 'If your app or website needs to connect locations with administrative areas, like constituencies or counties, MapIt can save you a lot of time. Available as a hosted API or a self-deployed web service, to suit your needs.'

**Comment by zarino** [comment]
@davewhiteland Done!

**Comment by dracos** [comment]
Few quick points:
- Typo: Ordnance, not Ordinance.
- The "like a pro" wording felt a bit jarring to me, as did the two headings starting "Is".
- MapIt UK doesn't contain any data from OpenStreetMap (it uses OSM maps on its front end, but I don't think that's what people would think by "UK data from"); you could say Office for National Statistics (ONS) instead. Conversely, on the as-a-service page, it only mentions the ONS, when the largest data provider is OS :)
